# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='netid',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
